# Generated by Django 5.0.14 on 2026-09-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockinterviewsession',
            name='topic',
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='current_phase',
            field=models.CharField(default='HR Screening', max_length=50),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='evaluation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='interview_mode',
            field=models.CharField(choices=[('Full Interview', 'Full Technical & HR Interview'), ('HR Screening', 'Phase 1: HR Screening'), ('Core CS', 'Phase 2: Core CS Round'), ('AI/ML + GenAI', 'Phase 3: AI/ML & Generative AI'), ('Project Deep Dive', 'Phase 4: Project Deep Dive'), ('System Design', 'Phase 5: System Design')], default='Full Interview', max_length=50),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='target_role',
            field=models.CharField(default='AI/ML Trainee | Generative AI Fresher', max_length=150),
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate')], max_length=20)),
                ('message', models.TextField()),
                ('round_name', models.CharField(default='HR Screening', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interview.mockinterviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
