# Generated by Django 5.0.14 on 2026-09-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0002_alter_resume_options_resume_extracted_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
