# Generated by Django 5.0.14 on 2026-09-05 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerroadmap',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='current_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='roadmap_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='careerroadmap',
            name='target_role',
            field=models.CharField(default='Software Development Engineer', max_length=150),
        ),
        migrations.AlterField(
            model_name='careerroadmap',
            name='title',
            field=models.CharField(default='Personalized 3-Month Roadmap', max_length=255),
        ),
    ]
