# Generated by Django 5.0.14 on 2026-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_careerroadmap_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerroadmap',
            old_name='roadmap_data',
            new_name='roadmap_json',
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='difficulty_level',
            field=models.CharField(default='Intermediate', max_length=50),
        ),
        migrations.AlterField(
            model_name='careerroadmap',
            name='target_role',
            field=models.CharField(default='Software Engineer', max_length=150),
        ),
        migrations.AlterField(
            model_name='careerroadmap',
            name='title',
            field=models.CharField(default='Personalized AI Career Roadmap', max_length=255),
        ),
    ]
